In [1]:
#!pip install shap
#!pip install sklearn
import pandas as pd
import numpy as np
import shap
import sklearn
import seaborn as sn
import matplotlib.pyplot as plt
from numpy.linalg import eig
from sklearn.decomposition import PCA

In [2]:
df_testing = pd.read_csv("./use_data/merged_dataset.csv")
df_testing['prob'] = np.nan
df_testing

,user_id,item_id,cat_id,seller_id,brand_id,time_stamp,action_type,age_range,gender,prob
0,149002,282,885,3791,1500.0,1111,0,5.0,2.0,NaN
1,149002,282,885,3791,1500.0,1107,0,5.0,2.0,NaN
2,109881,230,629,1,1662.0,820,0,4.0,0.0,NaN
3,109881,230,629,1,1662.0,820,0,4.0,0.0,NaN
4,109881,230,629,1,1662.0,820,0,4.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...
6544,73105,259,614,637,2603.0,1111,0,2.0,0.0,NaN
6545,403421,175,1181,4760,247.0,1111,0,3.0,1.0,NaN
6546,116738,186,267,1200,2276.0,1110,0,2.0,1.0,NaN
6547,116738,186,267,1200,2276.0,1101,0,2.0,1.0,NaN
6548,124951,184,656,145,3462.0,1111,0,0.0,0.0,NaN

In [3]:
df_training = pd.read_csv("./use_data/merged_dataset.csv")
df_training['label'] = -1
df_training

,user_id,item_id,cat_id,seller_id,brand_id,time_stamp,action_type,age_range,gender,label
0,149002,282,885,3791,1500.0,1111,0,5.0,2.0,-1
1,149002,282,885,3791,1500.0,1107,0,5.0,2.0,-1
2,109881,230,629,1,1662.0,820,0,4.0,0.0,-1
3,109881,230,629,1,1662.0,820,0,4.0,0.0,-1
4,109881,230,629,1,1662.0,820,0,4.0,0.0,-1
...,...,...,...,...,...,...,...,...,...,...
6544,73105,259,614,637,2603.0,1111,0,2.0,0.0,-1
6545,403421,175,1181,4760,247.0,1111,0,3.0,1.0,-1
6546,116738,186,267,1200,2276.0,1110,0,2.0,1.0,-1
6547,116738,186,267,1200,2276.0,1101,0,2.0,1.0,-1
6548,124951,184,656,145,3462.0,1111,0,0.0,0.0,-1

In [4]:
df_labels = pd.read_csv("./use_data/train_format1[161-320].csv")
df_labels

     user_id  merchant_id  label
0     108672         4760      0
1       6018          145      0
2     134532         3323      1
3     340104         3263      0
4     367500         4405      0
..       ...          ...    ...
164   327782         2277      0
165     8552         2277      0
166   177770         3323      1
167   125558         3323      0
168   276857         3323      0

[169 rows x 3 columns]

In [18]:
for index,row in df_training.iterrows():
    for index2,row2 in df_labels.iterrows():
        if((row['user_id'] == row2['user_id']) & (row['seller_id'] == row2['merchant_id'])):
            df_training.at[index, 'label'] = row2['label']

In [24]:
df_training = df_training[df_training['label'] != -1]
df_training

,user_id,item_id,cat_id,seller_id,brand_id,time_stamp,action_type,age_range,gender,label
31,379824,198,656,145,3462.0,1111,0,5.0,1.0,0
32,379824,198,656,145,3462.0,1111,0,5.0,1.0,0
33,379824,198,656,145,3462.0,1111,2,5.0,1.0,0
34,379824,198,656,145,3462.0,1110,0,5.0,1.0,0
35,379824,198,656,145,3462.0,1110,0,5.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...
6463,122632,175,1181,4760,247.0,1109,0,3.0,0.0,0
6464,122632,175,1181,4760,247.0,1108,0,3.0,0.0,0
6465,122632,175,1181,4760,247.0,1108,0,3.0,0.0,0
6508,95362,253,962,3263,626.0,1111,0,0.0,0.0,0
6515,99823,175,1181,4760,247.0,1110,0,2.0,0.0,0

In [26]:
expanded_testing = df_testing
expanded_training = df_training
expanded_testing.to_csv(index=False, header=True)
expanded_training.to_csv(index=False, header=True)

'user_id,item_id,cat_id,seller_id,brand_id,time_stamp,action_type,age_range,gender,label\r\n379824,198,656,145,3462.0,1111,0,5.0,1.0,0\r\n379824,198,656,145,3462.0,1111,0,5.0,1.0,0\r\n379824,198,656,145,3462.0,1111,2,5.0,1.0,0\r\n379824,198,656,145,3462.0,1110,0,5.0,1.0,0\r\n379824,198,656,145,3462.0,1110,0,5.0,1.0,0\r\n379824,198,656,145,3462.0,1110,0,5.0,1.0,0\r\n141307,175,1181,4760,247.0,1107,0,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1107,0,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1107,0,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1111,0,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1111,0,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1111,0,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1111,2,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1111,0,4.0,1.0,0\r\n141307,175,1181,4760,247.0,1111,0,4.0,1.0,0\r\n252255,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n309566,175,1181,4760,247.0,1111,2,5.0,0.0,0\r\n206032,281,1130,246,5380.0,1108,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1108,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1104,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1104,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1111,2,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1111,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1107,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1111,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1111,2,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1111,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1111,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1103,3,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1109,0,4.0,0.0,0\r\n206032,281,1130,246,5380.0,1105,0,4.0,0.0,0\r\n182119,279,898,3323,683.0,1111,0,4.0,1.0,0\r\n182119,279,898,3323,683.0,1110,0,4.0,1.0,0\r\n68225,279,898,3323,683.0,1108,0,5.0,1.0,1\r\n109919,198,656,145,3462.0,1105,0,4.0,0.0,0\r\n342023,190,664,1131,2350.0,1108,0,3.0,0.0,0\r\n342023,190,664,1131,2350.0,1108,0,3.0,0.0,0\r\n287829,175,1181,4760,247.0,1111,0,3.0,0.0,0\r\n255960,279,898,3323,683.0,1111,0,3.0,0.0,0\r\n380420,190,664,1131,2350.0,1105,0,3.0,0.0,0\r\n176150,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n176150,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n407671,219,349,1943,6208.0,1111,0,6.0,0.0,0\r\n407671,219,349,1943,6208.0,1111,2,6.0,0.0,0\r\n407671,219,349,1943,6208.0,1111,0,6.0,0.0,0\r\n407671,219,349,1943,6208.0,1109,3,6.0,0.0,0\r\n407671,219,349,1943,6208.0,1109,0,6.0,0.0,0\r\n407671,219,349,1943,6208.0,1109,0,6.0,0.0,0\r\n388332,285,1577,630,1905.0,520,0,5.0,0.0,0\r\n244552,278,1075,1210,6230.0,1111,2,2.0,1.0,0\r\n244552,278,1075,1210,6230.0,1111,0,2.0,1.0,0\r\n46507,224,614,4955,7924.0,1111,0,3.0,0.0,0\r\n46507,224,614,4955,7924.0,1111,0,3.0,0.0,0\r\n46507,224,614,4955,7924.0,1111,2,3.0,0.0,0\r\n191162,184,656,145,3462.0,1111,0,0.0,0.0,0\r\n191162,184,656,145,3462.0,1111,2,0.0,0.0,0\r\n174308,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n174308,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n174308,175,1181,4760,247.0,1111,2,0.0,1.0,0\r\n174308,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n134532,279,898,3323,683.0,1111,0,0.0,1.0,1\r\n355159,279,898,3323,683.0,1111,0,0.0,0.0,0\r\n62942,312,602,4129,5491.0,1103,0,2.0,0.0,0\r\n353962,184,656,145,3462.0,1111,0,6.0,0.0,0\r\n353962,184,656,145,3462.0,1111,0,6.0,0.0,0\r\n353962,184,656,145,3462.0,1111,0,6.0,0.0,0\r\n353962,184,656,145,3462.0,1111,2,6.0,0.0,0\r\n353962,184,656,145,3462.0,1111,0,6.0,0.0,0\r\n353962,184,656,145,3462.0,1111,0,6.0,0.0,0\r\n319670,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n319670,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n319670,175,1181,4760,247.0,1111,2,2.0,1.0,0\r\n210578,279,898,3323,683.0,1111,0,3.0,1.0,0\r\n210578,279,898,3323,683.0,1111,0,3.0,1.0,0\r\n210578,279,898,3323,683.0,1111,0,3.0,1.0,0\r\n101110,281,1130,246,5380.0,1111,2,4.0,0.0,0\r\n101110,281,1130,246,5380.0,1111,0,4.0,0.0,0\r\n101110,281,1130,246,5380.0,1111,0,4.0,0.0,0\r\n101110,281,1130,246,5380.0,1111,0,4.0,0.0,0\r\n149798,224,614,4955,7924.0,1108,0,2.0,0.0,0\r\n6018,184,656,145,3462.0,1111,0,6.0,0.0,0\r\n6018,184,656,145,3462.0,1111,0,6.0,0.0,0\r\n281262,279,898,3323,683.0,1109,0,4.0,1.0,0\r\n314519,219,349,1943,6208.0,1111,2,2.0,1.0,0\r\n205257,279,898,3323,683.0,1111,0,6.0,0.0,0\r\n117839,279,898,3323,683.0,1111,0,4.0,0.0,0\r\n46699,175,1181,4760,247.0,1111,2,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1109,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1109,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,3,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1106,3,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1106,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,0,4.0,1.0,0\r\n46699,175,1181,4760,247.0,1110,0,4.0,1.0,0\r\n238412,253,962,3263,626.0,1111,0,4.0,0.0,0\r\n238412,253,962,3263,626.0,1111,0,4.0,0.0,0\r\n238412,253,962,3263,626.0,1111,0,4.0,0.0,0\r\n238412,253,962,3263,626.0,1111,0,4.0,0.0,0\r\n156961,279,898,3323,683.0,1111,0,4.0,0.0,0\r\n45576,279,898,3323,683.0,1111,0,5.0,0.0,0\r\n45576,279,898,3323,683.0,1111,0,5.0,0.0,0\r\n45576,279,898,3323,683.0,1111,0,5.0,0.0,0\r\n45576,279,898,3323,683.0,1111,0,5.0,0.0,0\r\n45576,279,898,3323,683.0,1111,0,5.0,0.0,0\r\n45576,279,898,3323,683.0,1111,0,5.0,0.0,0\r\n214766,253,962,3263,626.0,1110,0,2.0,0.0,0\r\n214766,253,962,3263,626.0,1110,0,2.0,0.0,0\r\n5524,224,614,4955,7924.0,1111,0,3.0,0.0,1\r\n218669,279,898,3323,683.0,1111,0,0.0,2.0,0\r\n272518,224,614,4955,7924.0,1111,0,3.0,0.0,0\r\n277770,279,898,3323,683.0,1111,0,0.0,0.0,0\r\n386295,279,898,3323,683.0,1111,0,2.0,0.0,0\r\n402251,175,1181,4760,247.0,1103,0,2.0,1.0,0\r\n402251,175,1181,4760,247.0,1103,0,2.0,1.0,0\r\n402251,175,1181,4760,247.0,1109,0,2.0,1.0,0\r\n402251,175,1181,4760,247.0,1109,0,2.0,1.0,0\r\n254609,279,898,3323,683.0,1110,0,3.0,0.0,0\r\n254609,279,898,3323,683.0,1110,0,3.0,0.0,0\r\n254609,279,898,3323,683.0,1111,0,3.0,0.0,0\r\n254609,279,898,3323,683.0,1111,0,3.0,0.0,0\r\n84043,175,1181,4760,247.0,1111,0,2.0,0.0,0\r\n120820,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n291453,274,611,3593,777.0,1111,0,4.0,0.0,0\r\n280293,184,656,145,3462.0,1111,0,0.0,1.0,0\r\n291386,279,898,3323,683.0,1110,0,5.0,0.0,0\r\n313634,226,420,1784,7936.0,1111,0,5.0,0.0,0\r\n313634,226,420,1784,7936.0,1111,0,5.0,0.0,0\r\n313634,226,420,1784,7936.0,1111,0,5.0,0.0,0\r\n313634,226,420,1784,7936.0,1111,2,5.0,0.0,0\r\n60260,279,898,3323,683.0,1111,0,5.0,0.0,0\r\n112997,253,962,3263,626.0,1110,0,4.0,0.0,0\r\n112997,253,962,3263,626.0,1110,0,4.0,0.0,0\r\n305925,184,656,145,3462.0,1111,0,4.0,0.0,0\r\n305925,184,656,145,3462.0,1111,3,4.0,0.0,0\r\n199429,209,863,3766,1097.0,1110,0,0.0,0.0,0\r\n185381,279,898,3323,683.0,1111,0,3.0,1.0,0\r\n144281,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n144281,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n33618,319,1580,1536,3931.0,1111,0,3.0,0.0,0\r\n276857,279,898,3323,683.0,1111,0,4.0,1.0,0\r\n276857,279,898,3323,683.0,1111,2,4.0,1.0,0\r\n276857,279,898,3323,683.0,1111,0,4.0,1.0,0\r\n130186,279,898,3323,683.0,1111,0,0.0,0.0,1\r\n130186,279,898,3323,683.0,1110,0,0.0,0.0,1\r\n130186,279,898,3323,683.0,1110,0,0.0,0.0,1\r\n130186,279,898,3323,683.0,1110,3,0.0,0.0,1\r\n376338,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n376338,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n376338,175,1181,4760,247.0,1111,2,2.0,1.0,0\r\n376338,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n867,175,1181,4760,247.0,1111,0,3.0,0.0,0\r\n338395,175,1181,4760,247.0,1111,2,3.0,0.0,0\r\n338395,175,1181,4760,247.0,1108,0,3.0,0.0,0\r\n335587,219,349,1943,6208.0,1111,0,3.0,1.0,0\r\n335587,219,349,1943,6208.0,1111,0,3.0,1.0,0\r\n335587,219,349,1943,6208.0,1111,0,3.0,1.0,0\r\n335587,219,349,1943,6208.0,1111,0,3.0,1.0,0\r\n335587,219,349,1943,6208.0,1111,0,3.0,1.0,0\r\n335587,219,349,1943,6208.0,1111,2,3.0,1.0,0\r\n409283,279,898,3323,683.0,1111,0,0.0,0.0,0\r\n88275,170,1095,3828,1446.0,528,0,4.0,0.0,1\r\n165355,279,898,3323,683.0,1111,0,3.0,1.0,0\r\n165355,279,898,3323,683.0,1111,0,3.0,1.0,0\r\n165355,279,898,3323,683.0,1108,0,3.0,1.0,0\r\n165355,279,898,3323,683.0,1108,0,3.0,1.0,0\r\n165355,279,898,3323,683.0,1109,0,3.0,1.0,0\r\n55784,281,1130,246,5380.0,1111,0,4.0,0.0,1\r\n327782,211,1188,2277,1246.0,1105,0,3.0,1.0,0\r\n327782,211,1188,2277,1246.0,1105,0,3.0,1.0,0\r\n327782,211,1188,2277,1246.0,1110,0,3.0,1.0,0\r\n327782,211,1188,2277,1246.0,1110,0,3.0,1.0,0\r\n327782,211,1188,2277,1246.0,1110,0,3.0,1.0,0\r\n327782,211,1188,2277,1246.0,1110,0,3.0,1.0,0\r\n327782,211,1188,2277,1246.0,1108,0,3.0,1.0,0\r\n327782,211,1188,2277,1246.0,1111,2,3.0,1.0,0\r\n264657,184,656,145,3462.0,1111,0,4.0,0.0,0\r\n264657,184,656,145,3462.0,1111,0,4.0,0.0,0\r\n264657,184,656,145,3462.0,1111,0,4.0,0.0,0\r\n264657,184,656,145,3462.0,1111,2,4.0,0.0,0\r\n264657,184,656,145,3462.0,1111,0,4.0,0.0,0\r\n264657,184,656,145,3462.0,1111,0,4.0,0.0,0\r\n52751,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n52751,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n33745,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n33745,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n33745,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n33745,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n103980,277,1023,4282,7892.0,804,0,3.0,1.0,0\r\n316235,211,1188,2277,1246.0,1111,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1111,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1111,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1111,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1111,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1111,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1111,2,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1110,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1110,0,2.0,1.0,0\r\n316235,211,1188,2277,1246.0,1110,3,2.0,1.0,0\r\n380439,175,1181,4760,247.0,1110,0,6.0,0.0,0\r\n380439,175,1181,4760,247.0,1111,0,6.0,0.0,0\r\n86171,175,1181,4760,247.0,1106,0,2.0,1.0,0\r\n408759,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n408759,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n38606,175,1181,4760,247.0,1111,2,0.0,0.0,0\r\n38606,175,1181,4760,247.0,1111,0,0.0,0.0,0\r\n108672,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n35848,224,614,4955,7924.0,1109,0,2.0,0.0,0\r\n275260,175,1181,4760,247.0,1111,0,4.0,0.0,0\r\n275260,175,1181,4760,247.0,1111,0,4.0,0.0,0\r\n275260,175,1181,4760,247.0,1111,0,4.0,0.0,0\r\n275260,175,1181,4760,247.0,1111,0,4.0,0.0,0\r\n275260,175,1181,4760,247.0,1111,2,4.0,0.0,0\r\n275260,175,1181,4760,247.0,1111,2,4.0,0.0,0\r\n178063,175,1181,4760,247.0,1109,0,3.0,0.0,0\r\n419820,285,1577,630,1905.0,1110,0,4.0,2.0,0\r\n53531,279,898,3323,683.0,1111,0,0.0,1.0,0\r\n51728,291,1438,314,5946.0,1111,0,4.0,0.0,0\r\n51728,291,1438,314,5946.0,1111,0,4.0,0.0,0\r\n51728,291,1438,314,5946.0,1111,0,4.0,0.0,0\r\n51728,291,1438,314,5946.0,1111,0,4.0,0.0,0\r\n51728,291,1438,314,5946.0,1111,0,4.0,0.0,0\r\n51728,291,1438,314,5946.0,1111,2,4.0,0.0,0\r\n177770,279,898,3323,683.0,1110,0,3.0,1.0,1\r\n177770,279,898,3323,683.0,1110,0,3.0,1.0,1\r\n177770,279,898,3323,683.0,1111,0,3.0,1.0,1\r\n177770,279,898,3323,683.0,1107,0,3.0,1.0,1\r\n389062,221,598,4405,4631.0,1110,3,0.0,1.0,0\r\n389062,221,598,4405,4631.0,1110,0,0.0,1.0,0\r\n389062,221,598,4405,4631.0,1110,0,0.0,1.0,0\r\n389062,221,598,4405,4631.0,1111,0,0.0,1.0,0\r\n389062,221,598,4405,4631.0,1111,0,0.0,1.0,0\r\n389062,221,598,4405,4631.0,1111,2,0.0,1.0,0\r\n227925,277,1023,4282,7989.0,627,0,3.0,0.0,1\r\n383379,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n87972,175,1181,4760,247.0,1109,0,0.0,0.0,1\r\n165262,279,898,3323,683.0,1111,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1111,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,3,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,0,0.0,0.0,0\r\n165262,279,898,3323,683.0,1110,0,0.0,0.0,0\r\n97492,209,863,3766,1097.0,1111,0,0.0,0.0,0\r\n335815,198,656,145,3462.0,1111,0,2.0,1.0,0\r\n8552,211,1188,2277,1246.0,1111,0,0.0,0.0,0\r\n8552,211,1188,2277,1246.0,1103,0,0.0,0.0,0\r\n340708,211,1188,2277,1246.0,1111,0,4.0,0.0,0\r\n340708,211,1188,2277,1246.0,1111,0,4.0,0.0,0\r\n340708,211,1188,2277,1246.0,1111,0,4.0,0.0,0\r\n127492,253,962,3263,626.0,1111,0,2.0,0.0,0\r\n127492,253,962,3263,626.0,1111,0,2.0,0.0,0\r\n127492,253,962,3263,626.0,1111,0,2.0,0.0,0\r\n127492,253,962,3263,626.0,1111,0,2.0,0.0,0\r\n127492,253,962,3263,626.0,1111,2,2.0,0.0,0\r\n143411,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n143411,175,1181,4760,247.0,1111,2,0.0,1.0,0\r\n324110,224,614,4955,7924.0,1111,0,0.0,0.0,0\r\n324110,224,614,4955,7924.0,1111,2,0.0,0.0,0\r\n226193,175,1181,4760,247.0,1111,0,3.0,0.0,0\r\n108048,253,962,3263,626.0,1111,0,2.0,0.0,0\r\n108048,253,962,3263,626.0,1111,0,2.0,0.0,0\r\n355412,175,1181,4760,247.0,1110,0,0.0,0.0,0\r\n245259,190,664,1131,2350.0,1111,0,3.0,0.0,0\r\n251563,198,656,145,3462.0,1111,0,4.0,0.0,0\r\n81918,279,898,3323,683.0,603,0,4.0,0.0,0\r\n81918,279,898,3323,683.0,1111,0,4.0,0.0,0\r\n79189,277,1023,4282,7892.0,801,0,3.0,1.0,1\r\n173653,224,614,4955,7924.0,1111,0,3.0,1.0,0\r\n173653,224,614,4955,7924.0,1111,2,3.0,1.0,0\r\n283745,169,1505,4988,5738.0,1110,0,3.0,1.0,0\r\n283745,169,1505,4988,5738.0,1110,0,3.0,1.0,0\r\n97762,277,1023,4282,7892.0,804,0,3.0,1.0,1\r\n97762,277,1023,4282,7892.0,806,0,3.0,1.0,1\r\n5534,198,656,145,3462.0,1110,0,5.0,0.0,0\r\n317444,209,863,3766,1097.0,1110,0,4.0,0.0,0\r\n32155,186,267,1200,2276.0,1111,0,4.0,0.0,0\r\n32155,186,267,1200,2276.0,1110,0,4.0,0.0,0\r\n29443,277,1023,4282,7892.0,806,0,4.0,1.0,0\r\n364459,175,1181,4760,247.0,1101,0,4.0,1.0,0\r\n367079,279,898,3323,683.0,1111,0,4.0,1.0,0\r\n348030,279,898,3323,683.0,1111,0,2.0,0.0,0\r\n348030,279,898,3323,683.0,1111,0,2.0,0.0,0\r\n4755,175,1181,4760,247.0,1107,0,3.0,1.0,0\r\n132884,224,614,4955,7924.0,1111,0,3.0,0.0,0\r\n246586,186,267,1200,2276.0,1110,0,0.0,0.0,0\r\n246586,186,267,1200,2276.0,1110,0,0.0,0.0,0\r\n246586,186,267,1200,2276.0,1110,0,0.0,0.0,0\r\n246586,186,267,1200,2276.0,1110,0,0.0,0.0,0\r\n246586,186,267,1200,2276.0,1111,2,0.0,0.0,0\r\n102477,279,898,3323,683.0,1110,3,5.0,1.0,0\r\n102477,279,898,3323,683.0,1110,0,5.0,1.0,0\r\n274624,219,349,1943,6208.0,1111,2,2.0,1.0,0\r\n274624,219,349,1943,6208.0,1111,0,2.0,1.0,0\r\n274624,219,349,1943,6208.0,1111,0,2.0,1.0,0\r\n274624,219,349,1943,6208.0,1111,0,2.0,1.0,0\r\n274624,219,349,1943,6208.0,1105,0,2.0,1.0,0\r\n274624,219,349,1943,6208.0,1111,3,2.0,1.0,0\r\n175206,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n175206,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n175206,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n123833,175,1181,4760,247.0,1108,0,0.0,0.0,0\r\n367500,221,598,4405,4631.0,1110,0,2.0,1.0,0\r\n355808,279,898,3323,683.0,1111,0,3.0,0.0,0\r\n355808,279,898,3323,683.0,1110,0,3.0,0.0,0\r\n28461,184,656,145,3462.0,1111,0,0.0,0.0,0\r\n28461,184,656,145,3462.0,1111,2,0.0,0.0,0\r\n35597,269,530,2443,3654.0,1110,0,0.0,1.0,0\r\n352780,175,1181,4760,247.0,1111,2,3.0,1.0,0\r\n352780,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n78667,175,1181,4760,247.0,1026,0,2.0,1.0,0\r\n257735,312,602,4129,5491.0,1108,0,4.0,0.0,0\r\n165083,215,387,2820,6590.0,1001,0,6.0,1.0,0\r\n90821,279,898,3323,683.0,1111,0,4.0,1.0,0\r\n289430,312,602,4129,5491.0,1022,0,7.0,0.0,0\r\n251644,312,602,4129,5491.0,1108,0,3.0,0.0,0\r\n283392,279,898,3323,683.0,1111,0,4.0,1.0,1\r\n353886,175,1181,4760,247.0,1111,0,0.0,0.0,0\r\n353447,170,1095,3828,1446.0,601,0,0.0,0.0,0\r\n131122,315,1611,2642,8040.0,1111,0,0.0,0.0,0\r\n117310,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n117310,175,1181,4760,247.0,1111,2,2.0,1.0,0\r\n117310,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n59028,175,1181,4760,247.0,1110,0,3.0,1.0,0\r\n52647,184,656,145,3462.0,1111,0,2.0,2.0,0\r\n2448,279,898,3323,683.0,617,0,8.0,1.0,0\r\n2448,279,898,3323,683.0,617,0,8.0,1.0,0\r\n163584,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n295977,221,598,4405,4631.0,1101,0,0.0,0.0,0\r\n62849,279,898,3323,683.0,1110,0,2.0,1.0,0\r\n62849,279,898,3323,683.0,1109,0,2.0,1.0,0\r\n125558,279,898,3323,683.0,1111,0,4.0,0.0,0\r\n125558,279,898,3323,683.0,1111,0,4.0,0.0,0\r\n125558,279,898,3323,683.0,1030,0,4.0,0.0,0\r\n274843,198,656,145,3462.0,1111,0,3.0,1.0,0\r\n263873,184,656,145,3462.0,1109,0,0.0,2.0,0\r\n378696,175,1181,4760,247.0,1110,0,6.0,0.0,0\r\n239687,279,898,3323,683.0,1111,0,4.0,1.0,0\r\n148970,279,898,3323,683.0,524,3,3.0,1.0,1\r\n148970,279,898,3323,683.0,522,0,3.0,1.0,1\r\n148970,279,898,3323,683.0,529,0,3.0,1.0,1\r\n148970,279,898,3323,683.0,522,0,3.0,1.0,1\r\n148970,279,898,3323,683.0,522,0,3.0,1.0,1\r\n148970,279,898,3323,683.0,522,0,3.0,1.0,1\r\n257966,279,898,3323,683.0,1111,0,4.0,0.0,1\r\n401399,190,664,1131,2350.0,1109,0,3.0,0.0,1\r\n187060,190,664,1131,2350.0,1108,0,3.0,0.0,0\r\n15100,211,1188,2277,1246.0,1106,0,4.0,1.0,0\r\n218579,175,1181,4760,247.0,1111,0,0.0,1.0,0\r\n132803,191,1130,2226,7371.0,1109,0,2.0,0.0,0\r\n12875,279,898,3323,683.0,1105,0,3.0,1.0,0\r\n44606,184,656,145,3462.0,1111,0,0.0,0.0,0\r\n44606,184,656,145,3462.0,1111,0,0.0,0.0,0\r\n258575,253,962,3263,626.0,1110,0,0.0,0.0,0\r\n60425,175,1181,4760,247.0,1110,0,4.0,0.0,0\r\n60425,175,1181,4760,247.0,1110,0,4.0,0.0,0\r\n60425,175,1181,4760,247.0,1110,3,4.0,0.0,0\r\n60425,175,1181,4760,247.0,1111,0,4.0,0.0,0\r\n60425,175,1181,4760,247.0,1111,2,4.0,0.0,0\r\n60425,175,1181,4760,247.0,1111,0,4.0,0.0,0\r\n340104,253,962,3263,626.0,1111,0,2.0,0.0,0\r\n113078,175,1181,4760,247.0,1111,0,3.0,1.0,0\r\n229569,211,1188,2277,1246.0,1109,0,2.0,0.0,0\r\n229569,211,1188,2277,1246.0,1108,0,2.0,0.0,0\r\n229569,211,1188,2277,1246.0,1108,0,2.0,0.0,0\r\n229569,211,1188,2277,1246.0,1108,0,2.0,0.0,0\r\n229569,211,1188,2277,1246.0,1108,0,2.0,0.0,0\r\n229569,211,1188,2277,1246.0,1108,0,2.0,0.0,0\r\n289079,279,898,3323,683.0,1111,0,4.0,1.0,1\r\n72143,221,598,4405,4631.0,1026,0,3.0,0.0,0\r\n403117,175,1181,4760,247.0,1111,0,2.0,1.0,0\r\n36385,219,349,1943,6208.0,1111,2,0.0,0.0,0\r\n36385,219,349,1943,6208.0,1111,0,0.0,0.0,0\r\n122632,175,1181,4760,247.0,1109,0,3.0,0.0,0\r\n122632,175,1181,4760,247.0,1108,0,3.0,0.0,0\r\n122632,175,1181,4760,247.0,1108,0,3.0,0.0,0\r\n95362,253,962,3263,626.0,1111,0,0.0,0.0,0\r\n99823,175,1181,4760,247.0,1110,0,2.0,0.0,0\r\n'